
# 玩家防止玩家给无耐久的东西附魔绑定诅咒
绑定诅咒补丁:
  启用: true

# 玩家死亡时惩罚玩家
简易死亡惩罚:
  启用: true
  生效的世界:
    - "world"
    - "world_nether"
    - "world_the_end"

  # 设置玩家的基础属性
  玩家属性:
    血量: 2
    饱食度: 2
    饥饿值: 2
  # 给予缓慢与缓慢挖掘 30 秒
  药水效果:
    - "SLOW,30,0"
    - "SLOW_DIGGING,30,0"

磁盘空间检查:
  启用: true
  # 当磁盘空间低于 3G 时自动关服
  检测值: 3

地狱门处理器:
  启用: true

虚空掉落检查:
  启用: true

游戏规则管理: